apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container-1
        image: ghcr.io/univalle-software-development/backend/my-app-backend:latest
        ports:
        - containerPort: 3000
      - name: container-2
        image: ghcr.io/univalle-software-development/backend/my-app-backend:latest
        ports:
        - containerPort: 3001
