apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: stable
  template:
    metadata:
      labels:
        app: my-app
        version: stable
    spec:
      containers:
      - name: movie-pod
        image: ghcr.io/univalle-software-development/backend/my-app-backend:latest
        ports:
        - containerPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-canary
spec:
  replicas: 1  # 25% For the Canary 
  selector:
    matchLabels:
      app: my-app
      version: canary  # Label for canary version
  template:
    metadata:
      labels:
        app: my-app
        version: canary
    spec:
      containers:
      - name: my-container
        image: ghcr.io/univalle-software-development/backend/my-app-backend:latest    # Canary image
        ports:
        - containerPort: 3000
